name: Build PDF of the CV

on: [push, pull_request]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies with pip
        run: |
          pip install --upgrade pip
          pip install pyyaml bibtexparser jinja2
      
      - name: Update APT + install TeXLive
        run: |
          sudo apt-get -y update
          sudo apt-get -y install texlive-base texlive-binaries texlive-bibtex-extra texlive-font-utils texlive-fonts-extra texlive-fonts-recommended texlive-lang-english texlive-lang-european texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-plain-generic texlive-pstricks texlive-xetex
          sudo apt-get -y install make latexmk
          sudo apt-get -y install biber
          sudo apt-get -y update 
      
      - name: Build CV
        run: |
          mkdir -p build
          python generate.py cv.yaml
      
      - name: Render CV PDF
        run: |
          make buildpdf

      - name: Publish compiled PDF
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest compiled version of CV"
          files: |
            build/cv.pdf
