name: Build PDF of the CV

on: [push, pull_request]

jobs:
  compile-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update APT + install TeXLive
        run: |
          sudo apt update
          sudo apt install texlive-base texlive-binaries texlive-bibtex-extra texlive-font-utils texlive-fonts-extra texlive-fonts-recommended texlive-lang-english texlive-lang-european texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-plain-generic texlive-pstricks texlive-xetex
          sudo apt update

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies with pip
        run: |
          pip install --upgrade pip
          pip install yaml bibtexparser jinja2
      
      - name: Build CV
        run: |
          mkdir -p build
          python generate.py cv.yaml
      
      - name: Publish compiled PDF
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest compiled version of CV"
          files: |
            build/cv.pdf
